"""Tests for the v1.4 prompt-template engine and the deterministic inspector."""
from __future__ import annotations

import pytest

from sis_caro_humanizer.research.inspector import inspect_section
from sis_caro_humanizer.research.prompts import (
    FOOTER,
    list_templates,
    render,
)


def test_list_templates_shape():
    templates = list_templates()
    ids = {t.id for t in templates}
    assert ids == {
        "study_starter",
        "title_suggester",
        "methodology_reviewer",
        "data_analysis_interpreter",
        "discussion_drafter",
        "limitations_explorer",
        "reviewer_1_methodology",
        "reviewer_2_framing",
        "missing_inspector",
    }
    # Every template has at least one required field except… all of them have one.
    for t in templates:
        assert t.name
        assert t.fields, f"{t.id} has no fields"


def test_each_template_renders_with_required_fields():
    """Every template should render once we supply a non-empty value for
    each required field."""
    for meta in list_templates():
        ctx = {f.name: "placeholder content" for f in meta.fields if f.required}
        out = render(meta.id, ctx)
        assert out, f"{meta.id} produced empty output"
        # The footer is enforced.
        assert "Generated by humanizer v1.4" in out


def test_render_substitutes_provided_values():
    out = render(
        "study_starter",
        {
            "topic": "telerehabilitation post-stroke",
            "discipline": "physiotherapy",
            "audience": "Ghanaian PTs",
        },
    )
    assert "telerehabilitation post-stroke" in out
    assert "physiotherapy" in out
    assert "Ghanaian PTs" in out


def test_render_uses_defaults_for_optional_fields():
    out = render(
        "study_starter",
        {"topic": "stroke rehab", "discipline": "physiotherapy"},
    )
    # gap default per template: "(unspecified — propose one)"
    assert "(unspecified" in out


def test_render_missing_required_raises():
    with pytest.raises(KeyError) as exc_info:
        render("study_starter", {"discipline": "physiotherapy"})
    assert "topic" in str(exc_info.value)


def test_render_blank_required_raises():
    with pytest.raises(KeyError):
        render("study_starter", {"topic": "   ", "discipline": "physio"})


def test_render_unknown_template_raises():
    with pytest.raises(KeyError):
        render("does_not_exist", {})


def test_footer_enforced_once():
    """Even if a template happens to already include the footer, the
    renderer should not duplicate it."""
    out = render("title_suggester", {"abstract": "study of X"})
    # FOOTER text appears at most twice (once verbatim, once in trim) — no
    # double-print of the canonical footer line.
    canonical = "Generated by humanizer v1.4"
    assert out.count(canonical) == 1


def test_footer_format_includes_separator():
    out = render("title_suggester", {"abstract": "study of X"})
    # The footer rule includes the `---` separator line.
    assert "\n---\n" in out
    assert out.endswith(FOOTER) or out.rstrip().endswith(FOOTER.rstrip())


def test_inspector_finds_missing_methods_items():
    """A bare-bones methods section misses sample-size, ethics, and analysis."""
    section = "We interviewed staff at the hospital."
    findings = inspect_section(section, "methods")
    names = {f.name for f in findings}
    assert "sample_size_missing" in names
    assert "ethics_approval_missing" in names
    # And each finding carries a non-empty drill-down prompt.
    for f in findings:
        assert f.prompt
        assert "Generated by humanizer v1.4" in f.prompt


def test_inspector_skips_present_items():
    """Once the section reports the items, the inspector drops them."""
    section = (
        "We recruited n = 124 patients via purposive sampling. "
        "Ethics approval was obtained from the IRB (ref 12). "
        "Cronbach's alpha was 0.85. "
        "Thematic analysis was performed in NVivo."
    )
    findings = inspect_section(section, "methods")
    names = {f.name for f in findings}
    assert "sample_size_missing" not in names
    assert "ethics_approval_missing" not in names
    assert "instrument_validation_missing" not in names
    assert "analysis_plan_missing" not in names


def test_inspector_unknown_section_type_returns_empty():
    findings = inspect_section("anything", "title")
    assert findings == []
