"""End-to-end smoke tests for the v1.4 daemon routes (CONTRACT v1.4 §1)."""
from __future__ import annotations

import pytest
from fastapi.testclient import TestClient

from sis_caro_humanizer.scoring.external import DetectorResult
from sis_caro_humanizer.serve.app import create_app

TOKEN = "test-token"
HDRS = {"Authorization": f"Bearer {TOKEN}"}


@pytest.fixture
def client() -> TestClient:
    return TestClient(create_app(token=TOKEN))


# ---------------------------------------------------------------------------
# /v1/research/templates
# ---------------------------------------------------------------------------


def test_list_templates_requires_auth(client):
    r = client.get("/v1/research/templates")
    assert r.status_code == 401


def test_list_templates_returns_nine(client):
    r = client.get("/v1/research/templates", headers=HDRS)
    assert r.status_code == 200
    body = r.json()
    assert "templates" in body
    ids = {t["id"] for t in body["templates"]}
    assert "study_starter" in ids
    assert len(ids) == 9
    sample = body["templates"][0]
    assert "fields" in sample
    assert "name" in sample
    assert "description" in sample


# ---------------------------------------------------------------------------
# /v1/research/prompt
# ---------------------------------------------------------------------------


def test_prompt_renders_study_starter(client):
    r = client.post(
        "/v1/research/prompt",
        json={
            "template_id": "study_starter",
            "context": {
                "topic": "telerehabilitation post-stroke",
                "discipline": "physiotherapy",
            },
        },
        headers=HDRS,
    )
    assert r.status_code == 200
    body = r.json()
    assert "telerehabilitation" in body["prompt"]
    assert body["char_count"] == len(body["prompt"])
    assert "Generated by humanizer v1.4" in body["prompt"]


def test_prompt_missing_required_field_returns_400(client):
    r = client.post(
        "/v1/research/prompt",
        json={"template_id": "study_starter", "context": {"discipline": "x"}},
        headers=HDRS,
    )
    assert r.status_code == 400
    assert r.json()["error"] == "invalid_input"


def test_prompt_unknown_template_returns_400(client):
    r = client.post(
        "/v1/research/prompt",
        json={"template_id": "no_such_template", "context": {}},
        headers=HDRS,
    )
    assert r.status_code == 400


# ---------------------------------------------------------------------------
# /v1/research/inspect
# ---------------------------------------------------------------------------


def test_inspect_methods_finds_missing_pieces(client):
    r = client.post(
        "/v1/research/inspect",
        json={
            "section_text": "We interviewed staff at the hospital.",
            "section_type": "methods",
        },
        headers=HDRS,
    )
    assert r.status_code == 200
    body = r.json()
    names = {f["name"] for f in body["findings"]}
    assert "sample_size_missing" in names
    for f in body["findings"]:
        assert f["prompt"]


def test_inspect_unknown_section_type_returns_empty(client):
    r = client.post(
        "/v1/research/inspect",
        json={"section_text": "anything", "section_type": "abstract"},
        headers=HDRS,
    )
    assert r.status_code == 200
    assert r.json()["findings"] == []


# ---------------------------------------------------------------------------
# /v1/research/reviewer
# ---------------------------------------------------------------------------


def test_reviewer_r1_returns_prompt(client):
    r = client.post(
        "/v1/research/reviewer",
        json={"full_text": "This is a draft manuscript text.", "persona": "r1"},
        headers=HDRS,
    )
    assert r.status_code == 200
    prompt = r.json()["prompt"]
    assert "Reviewer 1" in prompt
    assert "draft manuscript" in prompt


def test_reviewer_r2_returns_prompt(client):
    r = client.post(
        "/v1/research/reviewer",
        json={"full_text": "Another draft.", "persona": "r2"},
        headers=HDRS,
    )
    assert r.status_code == 200
    assert "Reviewer 2" in r.json()["prompt"]


def test_reviewer_invalid_persona_returns_422(client):
    r = client.post(
        "/v1/research/reviewer",
        json={"full_text": "x", "persona": "r3"},
        headers=HDRS,
    )
    assert r.status_code in (400, 422)


# ---------------------------------------------------------------------------
# /v1/llm/run
# ---------------------------------------------------------------------------


def test_llm_run_unknown_backend_returns_422(client):
    r = client.post(
        "/v1/llm/run",
        json={"prompt": "hello", "backend": "alien"},
        headers=HDRS,
    )
    assert r.status_code in (400, 422)


def test_llm_run_unavailable_backend_returns_502(client, monkeypatch):
    """When the chosen backend is unconfigured, route should 502."""

    class FakeBackend:
        def is_available(self):
            return False

        def rewrite(self, *a, **kw):
            raise NotImplementedError

    monkeypatch.setattr(
        "sis_caro_humanizer.serve.routes.benchmark.get_backend",
        lambda name: FakeBackend(),
    )
    r = client.post(
        "/v1/llm/run",
        json={"prompt": "hi", "backend": "anthropic"},
        headers=HDRS,
    )
    assert r.status_code == 502
    assert r.json()["error"] == "backend_unavailable"


def test_llm_run_happy_path(client, monkeypatch):
    class FakeBackend:
        def is_available(self):
            return True

        def rewrite(self, prompt, *, system, model=None, timeout=120.0):
            return f"RESPONSE: {prompt}"

    monkeypatch.setattr(
        "sis_caro_humanizer.serve.routes.benchmark.get_backend",
        lambda name: FakeBackend(),
    )
    r = client.post(
        "/v1/llm/run",
        json={"prompt": "hello there", "backend": "ollama"},
        headers=HDRS,
    )
    assert r.status_code == 200
    body = r.json()
    assert body["output"].startswith("RESPONSE:")
    assert isinstance(body["elapsed_seconds"], float)


# ---------------------------------------------------------------------------
# /v1/benchmark
# ---------------------------------------------------------------------------


def test_benchmark_local_only(client):
    """No external header, no detectors → only the local humanizer score."""
    r = client.post(
        "/v1/benchmark",
        json={"text": "Some prose to score. " * 5, "detectors": []},
        headers=HDRS,
    )
    assert r.status_code == 200
    body = r.json()
    assert "humanizer" in body
    assert "score" in body["humanizer"]
    assert body["external"] == []


def test_benchmark_external_disabled_without_header(client):
    r = client.post(
        "/v1/benchmark",
        json={"text": "x", "detectors": ["gptzero"]},
        headers=HDRS,
    )
    assert r.status_code == 403
    assert r.json()["error"] == "external_disabled"


def test_benchmark_with_external_header(client, monkeypatch):
    """Mocked detector returns a result; the row is included."""

    class _FakeDetector:
        URL = "https://example.test/api"

        def detect(self, text, *, timeout=8.0):
            return DetectorResult(score=0.78, band="high", confidence=0.92)

    monkeypatch.setattr(
        "sis_caro_humanizer.serve.routes.benchmark.get_detector",
        lambda name: _FakeDetector(),
    )
    r = client.post(
        "/v1/benchmark",
        json={"text": "x" * 100, "detectors": ["gptzero"]},
        headers={**HDRS, "X-External-Benchmark": "yes"},
    )
    assert r.status_code == 200
    rows = r.json()["external"]
    assert rows and rows[0]["detector"] == "gptzero"
    assert rows[0]["score"] == 0.78


def test_benchmark_detector_failure_does_not_abort(client, monkeypatch):
    """One detector raising DetectorUnavailable still returns 200 and a row
    with `error` for the failing detector and no abort of the others."""

    from sis_caro_humanizer.scoring.external import DetectorUnavailable

    class _BadDetector:
        URL = "https://example.test/api"

        def detect(self, text, *, timeout=8.0):
            raise DetectorUnavailable("rate_limited")

    class _GoodDetector:
        URL = "https://example.test/api2"

        def detect(self, text, *, timeout=8.0):
            return DetectorResult(score=0.4, band="medium", confidence=None)

    def picker(name):
        if name == "gptzero":
            return _BadDetector()
        return _GoodDetector()

    monkeypatch.setattr("sis_caro_humanizer.serve.routes.benchmark.get_detector", picker)
    r = client.post(
        "/v1/benchmark",
        json={"text": "x" * 100, "detectors": ["gptzero", "sapling"]},
        headers={**HDRS, "X-External-Benchmark": "yes"},
    )
    assert r.status_code == 200
    rows = r.json()["external"]
    assert len(rows) == 2
    assert rows[0]["error"] == "rate_limited"
    assert "score" in rows[1]


# ---------------------------------------------------------------------------
# Auth coverage for the rest
# ---------------------------------------------------------------------------


def test_prompt_requires_auth(client):
    r = client.post("/v1/research/prompt", json={"template_id": "x", "context": {}})
    assert r.status_code == 401


def test_inspect_requires_auth(client):
    r = client.post("/v1/research/inspect", json={"section_text": "x", "section_type": "methods"})
    assert r.status_code == 401


def test_reviewer_requires_auth(client):
    r = client.post("/v1/research/reviewer", json={"full_text": "x", "persona": "r1"})
    assert r.status_code == 401


def test_llm_run_requires_auth(client):
    r = client.post("/v1/llm/run", json={"prompt": "x", "backend": "ollama"})
    assert r.status_code == 401


def test_benchmark_requires_auth(client):
    r = client.post("/v1/benchmark", json={"text": "x", "detectors": []})
    assert r.status_code == 401
