"""Prompt-template engine (v1.4).

A small, intentional renderer: each template is a markdown file under
``prompt_templates/`` with ``{{var}}`` placeholders and an optional
``{{var | default: "fallback"}}`` form. Variable metadata (which fields a
template needs) lives in a parallel ``_meta.yaml``.

The renderer enforces the standard footer (V1_4_CONTRACT §2.3): every
output ends with::

    ---
    Generated by humanizer v1.4 — paste this prompt into Claude / ChatGPT / Gemini.

If a template file already includes the footer, it is not duplicated.
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml

_TEMPLATES_DIR = Path(__file__).with_name("prompt_templates")
_META_FILE = _TEMPLATES_DIR / "_meta.yaml"

FOOTER = (
    "---\n"
    "Generated by humanizer v1.4 — paste this prompt into Claude / ChatGPT / "
    "Gemini.\n"
)


@dataclass
class TemplateField:
    name: str
    type: str = "string"
    required: bool = False


@dataclass
class TemplateMeta:
    id: str
    name: str
    description: str
    fields: list[TemplateField]


# Match {{var}}  or  {{var | default: "fallback"}}.
_PLACEHOLDER_RE = re.compile(
    r"\{\{\s*"
    r"(?P<name>[A-Za-z_][\w]*)"
    r"(?:\s*\|\s*default\s*:\s*\"(?P<default>[^\"]*)\")?"
    r"\s*\}\}"
)


@lru_cache(maxsize=1)
def _load_meta() -> dict[str, TemplateMeta]:
    if not _META_FILE.exists():
        return {}
    raw: dict[str, Any] = yaml.safe_load(_META_FILE.read_text(encoding="utf-8")) or {}
    out: dict[str, TemplateMeta] = {}
    for tid, body in raw.items():
        if not isinstance(body, dict):
            continue
        fields_raw = body.get("fields") or []
        fields = [
            TemplateField(
                name=str(f["name"]),
                type=str(f.get("type", "string")),
                required=bool(f.get("required", False)),
            )
            for f in fields_raw
            if isinstance(f, dict) and "name" in f
        ]
        out[tid] = TemplateMeta(
            id=str(tid),
            name=str(body.get("name", tid)),
            description=str(body.get("description", "")),
            fields=fields,
        )
    return out


def list_templates() -> list[TemplateMeta]:
    """Return every registered template, in the order they appear in
    ``_meta.yaml``."""
    return list(_load_meta().values())


def get_template_meta(template_id: str) -> TemplateMeta:
    meta = _load_meta()
    if template_id not in meta:
        raise KeyError(f"unknown template_id {template_id!r}")
    return meta[template_id]


def _read_template_body(template_id: str) -> str:
    path = _TEMPLATES_DIR / f"{template_id}.md"
    if not path.exists():
        raise KeyError(f"template file missing: {path.name}")
    return path.read_text(encoding="utf-8")


def _ensure_footer(rendered: str) -> str:
    text = rendered.rstrip()
    # Idempotent: if the template already supplies the canonical footer,
    # keep it; otherwise append.
    if text.endswith(FOOTER.rstrip()):
        if not text.endswith("\n"):
            text += "\n"
        return text
    if not text.endswith("\n"):
        text += "\n"
    return text + "\n" + FOOTER


def render(template_id: str, context: dict[str, Any]) -> str:
    """Render a template with the given context.

    Required variables missing from ``context`` raise ``KeyError`` (mapped
    to HTTP 400 by the daemon). Optional variables fall back to their
    ``default:`` literal, or the empty string if no default is declared.
    """
    meta = get_template_meta(template_id)
    body = _read_template_body(template_id)

    # Validate required fields up front so the error message is clean.
    for field in meta.fields:
        if field.required:
            value = context.get(field.name)
            if value is None or (isinstance(value, str) and not value.strip()):
                raise KeyError(f"missing required field {field.name!r}")

    def _sub(match: re.Match[str]) -> str:
        name = match.group("name")
        if name in context and context[name] not in (None, ""):
            return str(context[name])
        default = match.group("default")
        if default is not None:
            return default
        return ""

    rendered = _PLACEHOLDER_RE.sub(_sub, body)
    return _ensure_footer(rendered)


__all__ = [
    "FOOTER",
    "TemplateField",
    "TemplateMeta",
    "get_template_meta",
    "list_templates",
    "render",
]
